name: Docker Desktop Extension for Meshery
  # TODO 
  ##   1) Incorporate mesheryctl binaries into each DDE image

on:
  push:
    tags:
      - 'v*'  
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      # - '.github/**'
  workflow_dispatch:
    inputs:
      release-ver:
          description: 'Stable Release Version'     
          required: true
          default: 'v'
      stripped-release-ver:
          description: 'Stripped Stable Release Version'     
          required: true
          default: ''
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Release Channel
        id: release-channel
        run: |
          if [[ ${{ github.ref }} = refs/tags* ]]
          then
              echo "RELEASE_CHANNEL=stable" >> $GITHUB_ENV
          else
              echo "RELEASE_CHANNEL=edge" >> $GITHUB_ENV
          fi
          echo "Release channel determined to be $RELEASE_CHANNEL"
          echo "GIT_STRIPPED_VERSION=`echo ${{github.ref}} | cut -c 2-`" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: meshery/meshery-docker-desktop-extension
          flavor: |
            latest=false
            prefix=${{env.RELEASE_CHANNEL}}-
          tags: |
            type=raw,value={{sha}}
            type=semver,pattern={{version}},value=v${{env.GIT_STRIPPED_VERSION}}
            type=raw,value=v${{env.GIT_STRIPPED_VERSION}}
            type=raw,value={{tag}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=latest
          
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build and Push 
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:install/docker-desktop-extension"
          push: true
          build-args: |
            GIT_STRIPPED_VERSION=${{github.event.inputs.stripped-release-ver}}
            GIT_VERSION=${{github.event.inputs.release-ver}}
          tags: ${{ steps.meta.outputs.tags }}     
          platforms: linux/amd64,linux/arm64

      # - 
      #   name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: meshery/meshery-docker-desktop-extension  
      #     readme-filepath: /install/docker-desktop-extension/README.md 